spring.application.name=ExamenEntrevistaScotiabank
error.estado.invalido=El estado debe ser ACTIVO o INACTIVO
error.alumno.id.duplicado=El ID del alumno ya existe
mensaje.alumno.creado=Alumno guardado exitosamente con base de datos en memoria

# Configuración de H2 en memoria para R2DBC (Reactivo)
spring.r2dbc.url=r2dbc:h2:mem:///alumnosdb
spring.r2dbc.username=sa
spring.r2dbc.password=

# Deshabilitar JPA porque R2DBC no lo usa
spring.jpa.database-platform=
#spring.datasource.url=
#spring.datasource.driverClassName=

# Habilitar la consola web de H2 (Opcional, pero no funciona con R2DBC)

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.mode=always

# Configuración de Mysql para R2DBC (Reactivo)
#spring.r2dbc.url=r2dbc:mysql://localhost:3306/Entrevista
#spring.r2dbc.username=root
#spring.r2dbc.password=root
#spring.r2dbc.pool.enabled=true  # Habilitar pooling de conexiones si lo necesitas


#http://localhost:8080/h2-console.
