spring.application.name=ExamenEntrevistaScotiabank

error.estado.invalido=El estado debe ser ACTIVO o INACTIVO
error.alumno.id.duplicado=El ID del alumno ya existe

mensaje.alumno.creado=Alumno guardado exitosamente con colecciones



