spring.application.name=ExamenEntrevistaScotiabank
error.estado.invalido=El estado debe ser ACTIVO o INACTIVO
error.alumno.id.duplicado=El ID del alumno ya existe
mensaje.alumno.creado=Alumno guardado exitosamente con base de datos en memoria

# Configuración de H2 en memoria
spring.datasource.url=jdbc:h2:mem:alumnosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar la consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

